language: php
php:
  - '7.4.0'

branches:
  only:
    - master
    - Integration

script:
  - echo Integration termine
  - npm install && npm run publish

deploy:
  - php Back-end/Installation.php DB_HOST=host DB_NAME=name DB_CHARSET=charset DB_USER=user DB_PASSWORD=password DB_PORT=port
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: Integration

# after_deploy:
#   on: gh-pages
#   - php Back-end/Installation.php DB_HOST=host DB_NAME=name DB_CHARSET=charset DB_USER=user DB_PASSWORD=password DB_PORT=port